workflows:
  build:
    name: Build Workflow
    scripts:
      - name: Show APK and IPA Files
        script: |
          echo "Listing APK files:"
          ls -l build/app/outputs/flutter-apk/*.apk

          echo "Listing IPA files:"
          ls -l build/ios/Runner/*.ipa
